---
- name: Crear archivo de configuración en host remoto
  hosts: all
  gather_facts: false

  vars:
    vlan_id: "{{ vlan_id | default('666') }}"   # Obtiene vlan_id de AWX o usa '666'
    vlan_name: "{{ vlan_name | default('devil') }}" # Obtiene vlan_name de AWX o usa 'devil'
    remote_host: "10.9.9.199"                       # Define el host remoto

  tasks:
    - name: Crear archivo de configuración en host remoto
      become: true
      copy:
        dest: /etc/ansible/playbooks/configapi.txt
        content: |
          host={{ remote_host }}
          credentials_file=/etc/ansible/playbooks/credentials.txt
          vlan_id={{ vlan_id }}
          vlan_name={{ vlan_name }}
          enable_secret=

    - name: Ejecutar el playbook de Ansible remoto
      become: true
      command:
        cmd: ansible-playbook /etc/ansible/playbooks/catsw.yml