---
- name: Ejecutar Playbook Remoto desde AWX
  hosts: all
  gather_facts: false

  tasks:
    - name: Copiar el template config.txt.j2 desde el host remoto
      become: true
      copy:
        src: /etc/ansible/templates/config.txt.j2
        dest: /etc/ansible/playbooks/config.txt.j2
        remote_src: yes
      vars:
        vlan_id: "{{ vlan_id }}"
        vlan_name: "{{ vlan_name }}"

    - name: Ejecutar el playbook de Ansible remoto
      become: true
      command:
        cmd: ansible-playbook /etc/ansible/playbooks/catsw.yml 
      