---
- name: Crear archivo de configuración en host remoto
  hosts: all  # Ajusta esto al grupo de hosts en tu inventario
  gather_facts: false
  vars:
    vlan_id: "{{ vlan_id | default('666') }}"  # Valor por defecto si el survey falla
    vlan_name: "{{ vlan_name | default('devil') }}"  # Valor por defecto si el survey falla

  tasks:
    - name: Crear archivo de configuración en host remoto
      become: true
      copy:
        dest: /etc/ansible/playbooks/config.txt
        content: |
          host=10.9.9.199
          credentials_file=/etc/ansible/playbooks/credentials.txt
          vlan_id={{ vlan_id }}
          vlan_name={{ vlan_name }}
          report_file=/etc/ansible/playbooks/reporte.html
          enable_secret

    - name: Ejecutar el playbook de Ansible remoto
      become: true
      command:
        cmd: ansible-playbook /etc/ansible/playbooks/catsw.yml
      
          
      
         
      
      