---
- name: Ejecutar Playbook Remoto desde AWX
  hosts: all # Asegúrate de que este grupo incluya la máquina Linux de destino
  gather_facts: false # Opcional: Deshabilita la recopilación de hechos si no es necesaria

  tasks:
  
    - name: Generar archivo config.txt en el servidor remoto
      become: true
      template:
        src: /etc/ansible/templates/config.txt.j2  # Plantilla Jinja2 para config.txt
        dest: /etc/ansible/playbooks/config.txt
      vars:
        vlan_id: "{{ vlan_id }}"  # Variables del Survey
        vlan_name: "{{ vlan_name }}"

    - name: Ejecutar el playbook de Ansible remoto
      become: true
      command:
        cmd: ansible-playbook /etc/ansible/playbooks/catsw.yml 