---
- name: Ejecutar Playbook Remoto desde AWX
  hosts: all # Asegúrate de que este grupo incluya la máquina Linux de destino
  gather_facts: false # Opcional: Deshabilita la recopilación de hechos si no es necesaria

  tasks:
    - name: Crear directorio para el archivo de configuración (si no existe)
      become: true # Ejecutar como usuario con privilegios (ej: root)
      file:
        path: /etc/ansible/playbooks
        state: directory
        mode: '0755'
      
    - name: Generar archivo config.txt en el servidor remoto
      become: true
      template:
        src: config.txt.j2  # Plantilla Jinja2 para config.txt
        dest: /etc/ansible/playbooks/config.txt
      vars:
        vlan_id: "{{ vlan_id }}"  # Variables del Survey
        vlan_name: "{{ vlan_name }}"

    - name: Ejecutar el playbook de Ansible remoto
      become: true
      command:
        cmd: ansible-playbook /ruta/al/playbook/a/ejecutar.yml -i /ruta/al/inventario/remoto
      args:
        chdir: /home/usuario  # Opcional: Cambiar directorio antes de ejecutar