---
- name: Ejecutar Playbook Remoto desde AWX
  hosts: all
  gather_facts: false

  tasks:
    
    - name: Generar el archivo config.txt con las variables del survey base
      become: true
      template:
        src: /etc/ansible/playbooks/config.txt.j2  
        dest: /etc/ansible/playbooks/config.txt
        remote_src: yes
      vars:
        vlan_id: "{{ vlan_id }}"
        vlan_name: "{{ vlan_name }}"

    - name: Ejecutar el playbook de Ansible remoto
      become: true
      command:
        cmd: ansible-playbook /etc/ansible/playbooks/catsw.yml 
      
      