---
- name: Ejecutar Playbook Remoto desde AWX
  hosts: all
  gather_facts: false

  tasks:
    - name: Insertar variables del survey en el archivo config.txt
      become: true
      blockinfile:
        path: /etc/ansible/playbooks/config.txt
        block: |
          host=10.9.9.199
          credentials_file=/etc/ansible/playbooks/credentials.txt
          vlan_id={{ vlan_id }}
          vlan_name={{ vlan_name }}
          report_file=/etc/ansible/playbooks/reporte.html
          enable_secret=

    - name: Ejecutar el playbook de Ansible remoto
      become: true
      command:
        cmd: ansible-playbook /etc/ansible/playbooks/catsw.yml
      
      
         
      
      