---
- name: Obtener la IP del servidor
  hosts: all  # Se ejecutará en todos los hosts del inventario
  gather_facts: false  # No se necesitan facts para este ejemplo
  tasks:
    - name: Ejecutar comando para obtener la IP
      command: /bin/hostname -I  # Comando para obtener la dirección IP
      register: ip_output  # Guardar la salida del comando