- name: Verificar CPU y Memoria en Rocky Linux 9.5
  hosts: all
  gather_facts: false  # No se necesitan facts ya que usaremos comandos de shell
  tasks:
    - name: Obtener información de la CPU
      shell: lscpu
      register: cpu_info
      ignore_errors: yes

    - name: Mostrar información de la CPU
      debug:
        msg: |
          Detalles de la CPU:
          {{ cpu_info.stdout }}
      when: cpu_info.rc == 0  # Solo mostrar si el comando se ejecutó correctamente

    - name: Manejar errores de CPU
      debug:
        msg: "Error al obtener información de la CPU: {{ cpu_info.stderr }}"
      when: cpu_info.rc != 0  # Mostrar el error si el comando falló 0  # Mostrar el error si el comando falló