---
- name: Verificar CPU y Memoria en Rocky Linux 9.5
  hosts: all
  gather_facts: true
  tasks:
    - name: Obtener informacion de la CPU
      command: lscpu
      register: cpu_info
      ignore_errors: yes

    - name: Mostrar informacion de la CPU
      debug:
        msg: |
          Detalles de la CPU:
          {{ cpu_info.stdout_lines }}
      when: cpu_info.rc == 0  # Solo mostrar si el comando se ejecutó correctamente

    - name: Manejar errores de CPU
      debug:
        msg: "Error al obtener informacion de la CPU: {{ cpu_info.stderr }}"
      when: cpu_info.rc != 0  # Mostrar el error si el comando falló

    - name: Obtener informacion de la memoria
      command: free -m
      register: memory_info
      ignore_errors: yes

    - name: Mostrar informacion de la memoria
      debug:
        msg: |
          Detalles de la Memoria:
          {{ memory_info.stdout_lines }}
      when: memory_info.rc == 0  # Solo mostrar si el comando se ejecutó correctamente

    - name: Manejar errores de memoria
      debug:
        msg: "Error al obtener información de la memoria: {{ memory_info.stderr }}"
      when: memory_info.rc != 0  # Mostrar el error si el comando falló