---
- name: Ejecutar múltiples comandos en shell
  hosts: all        # Esto se aplicará a todos los hosts definidos en tu inventario
  gather_facts: false
  tasks:
    - name: Ejecutar varios comandos en el shell
      shell: |
        echo "Comenzando la ejecución de comandos..."
        date  # Obtener la fecha actual
        free -m  # Mostrar uso de memoria en MB
        df -h  # Mostrar uso del sistema de archivos
        echo "Ejecución completa."
      register: command_output

    - name: Mostrar salida de los comandos
      debug:
        msg: "{{ command_output.stdout_lines }}"