- name: Obtener la IP del servidor
  hosts: all  
  gather_facts: false  
  tasks:
    - name: Ejecutar comando para obtener la IP
      command: hostname -I  
      register: ip_output  

    - name: Mostrar la salida del comando
      debug:
        msg: "La dirección IP del servidor es: {{ ip_output.stdout }}"  