---
- name: Configurar VLAN en Switch Cisco mediante SSH
  hosts: all  # Se aplicará a todos los hosts en el inventario
  gather_facts: false
  vars_prompt:
    - name: "vlan_id"
      prompt: "Ingrese el ID de la VLAN (por ejemplo 10)"
      private: no
    - name: "vlan_name"
      prompt: "Ingrese el nombre de la VLAN (por ejemplo RED)"
      private: no

  tasks:
    - name: Validar si la VLAN existe
      shell: "show vlan | include VLAN {{ vlan_id }}"
      register: vlan_check
      ignore_errors: yes

    - name: Crear VLAN si no existe
      shell: |
      configure terminal
      vlan {{ vlan_id }}
      name {{ vlan_name }}
      exit
      show vlan | include VLAN {{ vlan_id }}
      when: vlan_check.stdout == ""
      register: vlan_creation_result

    - name: Mostrar mensaje de éxito al crear VLAN
      debug:
        msg: "La VLAN {{ vlan_id }} con nombre '{{ vlan_name }}' ha sido creada."
      when: vlan_creation_result.rc == 0

    - name: Mostrar mensaje de VLAN existente
      debug:
        msg: "La VLAN {{ vlan_id }} ya existe. No se realizó ninguna acción."
      when: vlan_check.stdout != ""

    - name: Mostrar error si falla la creación
      debug:
        msg: "Error al crear la VLAN: {{ vlan_creation_result.stderr }}"
      when: vlan_creation_result.rc != 0