---
- name: Configurar VLAN en Switch Catalyst Cisco
  hosts: all  # Se aplicará a todos los hosts definidos en el inventario
  gather_facts: false
  vars_prompt:
    - name: "vlan_id"
      prompt: "Ingrese el ID de la VLAN (por ejemplo, 255)"
      private: no
    - name: "vlan_name"
      prompt: "Ingrese el nombre de la VLAN (por ejemplo, tmdemo)"
      private: no

  tasks:
    - name: Validar si la VLAN existe
      shell: |
        ssh -o StrictHostKeyChecking=no {{ ansible_ssh_user }}@{{ inventory_hostname }} "show vlan | include VLAN {{ vlan_id }}"
      register: vlan_check
      ignore_errors: yes

    - name: Crear VLAN si no existe
      shell: |
        ssh -o StrictHostKeyChecking=no {{ ansible_ssh_user }}@{{ inventory_hostname }} <<-EOF
            configure terminal
            vlan {{ vlan_id }}
            name {{ vlan_name }}
            exit
            show vlan | include VLAN {{ vlan_id }}
        EOF
      when: vlan_check.stdout == ""
      register: vlan_creation_result

    - name: Mostrar mensaje de éxito al crear VLAN
      debug:
        msg: "La VLAN {{ vlan_id }} con nombre '{{ vlan_name }}' ha sido creada."
      when: vlan_creation_result.rc == 0

    - name: Mostrar mensaje si la VLAN ya existe
      debug:
        msg: "La VLAN {{ vlan_id }} ya existe. No se realizó ninguna acción."
      when: vlan_check.stdout != ""

    - name: Mostrar error si falla la creación
      debug:
        msg: "Error al crear la VLAN: {{ vlan_creation_result.stderr }}"
      when: vlan_creation_result.rc != 0