# TMCONSULTING-CREACION DE VLAN
---
- name: Configurar VLAN SOLICTADA DEMO TMCONSULTING
  hosts: all
  gather_facts: no
  tasks:
    -name: Configurar VLAN 100 switches catalyst TMCONSULTING DEMO
      ios_config:
        lines:
          - vlan 105
          - name tmdemo
        save_when: modified