# TMCONSULTING-CREACION DE VLAN
---
- name: Configurar VLAN
  hosts: all
  gather_facts: no
  tasks:
    - name: Configurar VLAN 100 switches catalyst
      ios_config:
        lines:
          - vlan 105
          - name tmdemo
        save_when: modified